### ISSUE TITLE
Downside of Using One Context per Goroutine?

### ISSUE THREAD

**Issue by check-rawit** [twpayne/go-geos#128]
Hi, I’m wondering if there are any downsides to using one context per goroutine compared to using one global context for all goroutines?

**Comment by twpayne** [comment]
Each context is protected by a mutex so only one method call can be made at a time.

Using one context per goroutine will likely result in the best performance, at the expense of increased memory usage.

Care must be taken when mixing geometries from different contexts. If a method is called with geometries from two different contexts then both must be locked. go-geos locks contexts in argument order, which can lead to a deadlock in some situations, for example:

```
context1 := geos.NewContext()
context2 := geos.NewContext()
geom1 := context1.NewEmptyPoint()
geom2 := context2.NewEmptyPoint()
go func() {
    geom2.Equals(geom1) // Locks context1 then locks context2.
}()
geom1.Equals(geom2) // Locks context2 then locks context1.
```

In this case, both `.Equals` calls can deadlock if the following sequence of events occurs:

```go
/* in main */      geom1.context.Lock() // In geom1.Equals(geom2)
/* in goroutine */ geom2.context.Lock() // In geom2.Equals(geom1)
/* in main */      geom2.context.Lock() // In geom1.Equals(geom2) DEADLOCK
```
