### ISSUE TITLE
geos.Geom does not implement the Scanner and Valuer interfaces

### ISSUE THREAD

**Issue by xiaoming-master** [twpayne/go-geos#133]
geos.Geom does not implement the Scanner and Valuer interfaces, and some errors will occur when I use some orm frameworks (such as gorm) to operate geos.Geom objects.
[error] invalid field found for struct main.Waypoint's field Geom: define a valid foreign key for relations or implement the Valuer/Scanner interface

**Comment by twpayne** [comment]
Exactly.

There is also [pgx-geos](https://github.com/twpayne/pgx-geos) if you're using the pgx database driver.

**Comment by xiaoming-master** [comment]
I use go-shapefile to read data of geom.T type from the shapefile, then convert this data to wkb format, and then convert the wkb format data to geometry.Geometry. Is there a simple way to achieve this?

**Comment by twpayne** [comment]
You can use [go-geobabel](https://github.com/twpayne/go-geobabel) to convert between Go geometry formats, but your current approach of round-tripping via WKB is reasonable.
