### ISSUE TITLE
Difference between two polygons

### ISSUE THREAD

**Issue by msackman-verna** [twpayne/go-geos#38]
Thank you for all your work on this code base - extremely useful.

I need the difference (subtract) operator - https://libgeos.org/doxygen/classgeos_1_1geom_1_1Geometry.html#abb63e4f8f5510d4c00a1c3624aec9431

I can't see that it's exposed, unless I'm missing something. I'm happy to look into adding this, but judging by the other issue you've recently dealt with, it looks like it might be faster for you to do it? If not, please let me know and I'll have a go.

**Comment by twpayne** [comment]
Flattery will get you everywhere :)

Fixed in #39 and I've tagged version `v0.6.0`.
