### ISSUE TITLE
SymDifference between two polygons

### ISSUE THREAD

**Issue by msackman-verna** [twpayne/go-geos#42]
Me again!

Is there any chance I could offer you more flattery and request the symmetric difference operator?
https://libgeos.org/doxygen/geos__c_8h.html#a9738f1df1614be36a3ef1e523b93f0f5
(Obviously I can work around this for now, given Difference is already in and working, just at a slight cpu cost)

Enormous thanks! :grin:

**Comment by twpayne** [comment]
Added in #43 and tagged `v0.7.0`.
