### ISSUE TITLE
Include `concaveHullByLength` 

### ISSUE THREAD

**Issue by zedfmario** [twpayne/go-geos#78]
Hi there, @twpayne 

Would it be possible to include `concaveHullByLength` in the library?

> Refer to https://libgeos.org/doxygen/3.11/classgeos_1_1algorithm_1_1hull_1_1ConcaveHull.html#ada45f68340212afa6984e310f7a560a9

**Comment by zedfmario** [comment]
I've opened an issue: https://github.com/libgeos/geos/issues/849

**Comment by zedfmario** [comment]
It's supposed to be included in libgeos, according to https://github.com/libgeos/geos/issues/849#issuecomment-1474525181

**Comment by twpayne** [comment]
That PR was merged three days ago. The latest version of GEOS is 3.11.2, which was released five days ago, so it is not in a release version of GEOS. You have to wait for a released version of GEOS (of course you can use an unreleased version locally).
