### ISSUE TITLE
function not found

### ISSUE THREAD

**Issue by ruierzhao** [twpayne/go-geos#95]
when I try to build my application, it get "cannot use _Ctype_ulong(len(wkb)) (value of type _Ctype_ulong) as _Ctype_ulonglong value in variable declaration",maybe it is my `GEOS` version?

**Comment by twpayne** [comment]
You need to include more information if you want people to help you.

What operating system are you using? What C compiler? What version of GEOS?

**Comment by ruierzhao** [comment]
Thank you for your reply.Firstly, I am using Windows 10. Because I am not good at C/C++, I am using the `geos_ c. Lib` included in the `GDAL` library compiled by `vcpkg`.So I'm not sure about the specific version of the `geos` library. Just when I compiling my go application, there was an error like above.I hope I have already made it clear. Now I'm trying to use another library [geoos](https://github.com/spatial-go/geoos) to complete my work. I plan to try studing this lib in the future. thanks very much.

**Comment by twpayne** [comment]
Ah, I don't know much about Windows development. You'll likely have more success with macOS or Linux.

Can you try #97? This may fix the problem.
